AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - "test/**/*_test.rb"
    - "*.gemspec"

Metrics/ClassLength:
  Exclude:
    - "test/**/*_test.rb"

Metrics/LineLength:
  Max: 120
  Exclude:
    - sftp_wrapper.gemspec

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
